name: React-deployment demo
on:
  push:
    branches: 
      - main
      
jobs:
  Sample-test:
    runs-on: self-hosted
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Git Pull
        run: git pull && git checkout main

      - name: Variable to Files
        run: eval "${{ vars.NPM_INSTALL }}"

        env:
          REACT_APP_API_URL: "${{ vars.API_URL }}"
          REACT_APP_TEST_URL: "${{ vars.TEST_URL }}"
          REACT_APP_BACK_URL: "${{ vars.BACK_URL }}"
          REACT_APP_FRONT_URL: "${{ vars.FRONT_URL }}"
          REACT_APP_SIDE_URL: "${{ vars.Side hello world }}"
            
      - name: Run the app
        run: |
            eval "${{ vars.PM2_DELETE }}"
            eval "${{ vars.PM2_START }}"
