name: React-deployment demo
on:
  push:
    branches: 
      - main
      
jobs:
  Sample-test:
    runs-on: self-hosted
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Git Pull
        run: git pull && git checkout main

      - name: Variable to Files
        run: |
            eval "${{ vars.NPM_INSTALL }}"
            eval "${{ vars.PM2_DELETE }}"
            eval "${{ vars.PM2_START }}"
